name: Проверка репозитория
on: [push]
jobs:
  tests:
    name: Тесты скриптов
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Тест работоспособности кода
      run: |
        chmod +x hw.sh
        ./hw.sh
    - name: Тест установки утилит
      run: |
        chmod +x install_check.sh
        ./install_check.sh
