name: Проверка скрипта на работоспособность
on: [push]
jobs:
  tests:
    name: Тесты скрипта
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Тест работоспособности кода
      run: |
        chmod +x runcode_check.sh
        ./runcode_check.sh
    - name: Тест установки утилит
      run: |
        chmod +x install_check.sh
        ./install_check.sh
    - name: Тест проверки загрузки изображений
      run: |
        chmod +x download_check.sh
        ./download_check.sh
    - name: Тест проверки сохранения гифки
      run: |
        chmod +x makegif_check.sh
        ./makegif_check.sh
    - name: Тест установки утилиты
      run: |
        chmod +x dont_install.sh
        ./dont_install.sh
