name: Проверка скрипта на работоспособность
on: [push]
jobs:
  tests:
    name: Тесты скрипта
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Тест работоспособности кода
      run: |
        chmod +x hw.sh
        ./hw.sh
    - name: Тест установки утилит
      run: |
        chmod +x install_check.sh
        ./install_check.sh
    - name: Тест проверки загрузки изображений
      run: |
        chmod +x download_check.sh
        ./download_check.sh
