name: Проверка скрипта на работоспособность
on: [push]
jobs:
  tests:
    name: Тесты скрипта
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Тест работоспособности кода
      run: |
        chmod +x runcode_check.sh
        ./runcode_check.sh
    - name: Тест установки утилит
      run: |
        chmod +x install_check.sh
        ./install_check.sh
    - name: Тест проверки загрузки изображений
      run: |
        chmod +x download_check.sh
        ./download_check.sh
    - name: Тест проверки сохранения гифки
      run: |
        chmod +x makegif_check.sh
        ./makegif_check.sh
    - name: Тест на отсутствие папки
      run: |
        rm -rf non-existen_people
        chmod -w .
        # Запрещаем создание папки для сохранения изображений
        chmod +x ./runcode_check.sh
        ./runcode_check.sh
    - name: Тест один из файлов изображений отсутствует
      run: |
        #!/bin/bash

        # Предположим, что установка imagemagick и jq выполнена успешно
        # Создадим файл с неправильным именем в папке "non-existen_people"
        touch non-existen_people/.jpg

        # Запустим скрипт и сохраняем его вывод в файл
        ./runcode_check.sh > output.txt

        # Проверим, что вывод содержит "NO" и сообщение об ошибке для скачивания изображений
        if grep -q "NO" output.txt && grep -q "No such file or directory" output.txt; then
         echo "Test passed"
            else
          echo "Test failed"
          fi
